//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LwCoreMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LwCoreMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lw.LwCoreMessagesResources", typeof(LwCoreMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal application error has occured. The application cannot continue. Description: &apos;{0}&apos;..
        /// </summary>
        public static string CriticalMessageInternalError {
            get {
                return ResourceManager.GetString("CriticalMessageInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is in error. Description: &apos;{0}&apos;..
        /// </summary>
        public static string ErrorMessageRequestError {
            get {
                return ResourceManager.GetString("ErrorMessageRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request at offset &apos;{0}&apos; is null..
        /// </summary>
        public static string ErrorMessageRequestNullError {
            get {
                return ResourceManager.GetString("ErrorMessageRequestNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request at offset &apos;{0}&apos; has an invalid property &apos;{1}&apos;. Message: &apos;{2}&apos;..
        /// </summary>
        public static string ErrorMessageRequestParameterError {
            get {
                return ResourceManager.GetString("ErrorMessageRequestParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request at offset &apos;{0}&apos; has a null property &apos;{1}&apos;..
        /// </summary>
        public static string ErrorMessageRequestParameterNullError {
            get {
                return ResourceManager.GetString("ErrorMessageRequestParameterNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request at offset &apos;{0}&apos; has a property &apos;{1}&apos; whose value is out the range of valid values..
        /// </summary>
        public static string ErrorMessageRequestParameterOutOfRangeError {
            get {
                return ResourceManager.GetString("ErrorMessageRequestParameterOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ApplicationMessageCodeAttribute was placed on type member incorrectly. The member must be an Int64 field or property. Member &apos;{1}&apos; of Type &apos;{0}&apos;..
        /// </summary>
        public static string WarningMessageInvalidMessageCodeAttributeMember {
            get {
                return ResourceManager.GetString("WarningMessageInvalidMessageCodeAttributeMember", resourceCulture);
            }
        }
    }
}
