//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error occured while trying to get all instances of type {0}..
        /// </summary>
        public static string ActivateAllExceptionMessage {
            get {
                return ResourceManager.GetString("ActivateAllExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error occured while trying to get instance of type {0}, key &quot;{1}&quot;..
        /// </summary>
        public static string ActivationExceptionMessage {
            get {
                return ResourceManager.GetString("ActivationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resove an instance of type &apos;{0}&apos; in the component container..
        /// </summary>
        public static string ERROR_Extensions_CantResolveType {
            get {
                return ResourceManager.GetString("ERROR_Extensions_CantResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Instance&apos; method named &apos;{1}&apos; not found for type &apos;{0}&apos;..
        /// </summary>
        public static string Exception_ArgumentException_InstanceMethodNotFoundForType {
            get {
                return ResourceManager.GetString("Exception_ArgumentException_InstanceMethodNotFoundForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method named &apos;{1}&apos; of type &apos;{0}&apos; must have a first parameter of type &apos;System.Object&apos; and a second parameter of type &apos;{2}&apos;..
        /// </summary>
        public static string Exception_ArgumentException_NotHandlerMethod {
            get {
                return ResourceManager.GetString("Exception_ArgumentException_NotHandlerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Static&apos; method named &apos;{1}&apos; not found for type &apos;{0}&apos;..
        /// </summary>
        public static string Exception_ArgumentException_StaticMethodNotFoundForType {
            get {
                return ResourceManager.GetString("Exception_ArgumentException_StaticMethodNotFoundForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested value &apos;{0}&apos; was not found..
        /// </summary>
        public static string Exception_EnumOperations_Parse_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Exception_EnumOperations_Parse_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base message code &apos;{0}&apos; is greater than the maximum allowed value when UseLocalSeverityCodes is chosen. The maximum value is &apos;0xFFF&apos;..
        /// </summary>
        public static string Exception_FormatException_ExceededMaxBaseMessageCode {
            get {
                return ResourceManager.GetString("Exception_FormatException_ExceededMaxBaseMessageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a message priority. The specified message severity, &apos;{0}&apos; is a custom severity..
        /// </summary>
        public static string Exception_FormatException_MustSpecifyPriority {
            get {
                return ResourceManager.GetString("Exception_FormatException_MustSpecifyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no matching element..
        /// </summary>
        public static string Exception_InvalidOperation_NoMatch {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; instance has not been initialized..
        /// </summary>
        public static string Exception_InvalidOperation_NotInitialized {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown in the static constructor of &apos;{0}&apos;.\nException Type &apos;{1}&apos;.\nException Message: &apos;{2}&apos;\nStack Trace: &apos;{3}&apos;..
        /// </summary>
        public static string Exception_InvalidOperation_StaticConstructorExcepted {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_StaticConstructorExcepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enum &apos;{0}&apos; value &apos;{1}&apos; is invalid in this context..
        /// </summary>
        public static string ExceptionOperations_CreateEnumOutOfRangeMessage_EnumOutOfRanage {
            get {
                return ResourceManager.GetString("ExceptionOperations_CreateEnumOutOfRangeMessage_EnumOutOfRanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationMessageExceptions can only be created if there are errors in the argument list or in the call context..
        /// </summary>
        public static string InternalError_CreatedExceptionWithNoErrors {
            get {
                return ResourceManager.GetString("InternalError_CreatedExceptionWithNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Messages:.
        /// </summary>
        public static string LogItem_Message_ApplicationMessages {
            get {
                return ResourceManager.GetString("LogItem_Message_ApplicationMessages", resourceCulture);
            }
        }
    }
}
